language: python
dist: precise
python:
  - "2.7"
  - "3.4"
  - "3.6"
  - "pypy"
services:
  - mysql
  - redis-server
before_install:
  - pip install tox==1.9.2
before_script:
  # enable row-based binlog
  - sudo touch /etc/mysql/conf.d/replication.cnf
  - sudo chmod 777 /etc/mysql/conf.d/replication.cnf
  - echo '[mysqld]' > /etc/mysql/conf.d/replication.cnf
  - echo 'log-bin = mysql-bin' >> /etc/mysql/conf.d/replication.cnf
  - echo 'server-id = 1' >> /etc/mysql/conf.d/replication.cnf
  - echo 'binlog-format = row'  >> /etc/mysql/conf.d/replication.cnf
  - sudo chmod 700 /etc/mysql/conf.d/replication.cnf
  - sudo service mysql restart
script:
  - tox -v
